---

- name: Install package
  package:
    name: "{{ logrotate_pkg }}"
  tags:
    - logrotate_pkg

- name: Create individual config files
  template:
    src: logrotate.conf.j2
    dest: "{{ logrotate_config_dir }}/{{ item.file }}"
    owner: "{{ item.owner | default(logrotate_owner) }}"
    group: "{{ item.group | default(logrotate_group) }}"
    mode: "{{ item.mode | default(logrotate_mode) }}"
  loop: "{{ logrotate_config }}"
  tags:
    - logrotate_config
